import type { DocumentIssue } from '../../../data/schemas/envelope'
import type { StrategiaData } from '../../../data/schemas/strategia'
import { checkClientView, type ClientView } from '../clientView'

/**
 * KLI-STRATEGIA rendering. The client view follows WZR-STRATEGIA's projection:
 * 800–1100 words, the strategic choice explained in the first 150 words, the
 * proof architecture kept internal (the client sees short reasons to believe
 * and limits at the main promises, never the evidence matrix). The view never
 * overwrites the data.
 */

const T = {
  pl: {
    title: 'Strategia komunikacji',
    choice: 'Nasz wybór',
    deprioritized: 'Czego świadomie nie eksponujemy',
    tension: 'Najważniejsze napięcie zakupowe',
    wants: 'Odbiorca chce',
    barrier: 'Co go powstrzymuje',
    statusQuo: 'Koszt pozostania przy obecnym stanie',
    objection: 'Przykładowa obiekcja',
    hypothesis: 'hipoteza do sprawdzenia',
    customerVoice: 'głos klientów',
    uvp: 'Propozycja wartości',
    mechanism: 'Mechanizm',
    alternative: 'Wobec alternatywy',
    reasonToBelieve: 'Dlaczego wierzyć',
    useConditions: 'Warunki użycia',
    options: 'Rozważone i odrzucone kierunki',
    advantage: 'zaleta',
    rejected: 'odrzucone, bo',
    messages: 'Hierarchia przekazu',
    mainPromise: 'Główna obietnica',
    supporting: 'Przekazy wspierające',
    order: 'Kolejność wyjaśniania',
    pillars: 'Filary tematyczne',
    goal: 'cel',
    question: 'pytanie odbiorcy',
    allowed: 'co pokazujemy',
    exclusions: 'czego nie',
    channel: 'Rola kanału',
    contact: 'ścieżka kontaktu',
    limits: 'granice',
    measurement: 'Hipoteza pomiaru',
    signals: 'sygnały',
    baseline: 'punkt odniesienia',
    unknownBaseline: 'brak — bez danych wewnętrznych nie ustalamy celu liczbowego',
    causality: 'granica wnioskowania',
    boundaries: 'Granice twórcze',
    notPromoted: 'Nie promujemy',
    prohibited: 'Nie obiecujemy',
    creativity: 'Dozwolona swoboda',
    rights: 'Prawa do materiałów',
    assumptions: 'Otwarte założenia',
    proofArchitecture: 'Architektura dowodów (wewnętrzna)',
    issues: 'Luki i ograniczenia',
    support: { declared_method: 'deklarowana metoda', documented_capability: 'udokumentowana zdolność', demonstrated_result: 'wykazany wynik' },
  },
  en: {
    title: 'Communication strategy',
    choice: 'Our choice',
    deprioritized: 'What we deliberately do not push',
    tension: 'The key buying tension',
    wants: 'The buyer wants',
    barrier: 'What holds them back',
    statusQuo: 'The cost of staying as is',
    objection: 'An illustrative objection',
    hypothesis: 'hypothesis to test',
    customerVoice: 'customer voice',
    uvp: 'Value proposition',
    mechanism: 'Mechanism',
    alternative: 'Against the alternative',
    reasonToBelieve: 'Reason to believe',
    useConditions: 'Conditions of use',
    options: 'Directions considered and rejected',
    advantage: 'advantage',
    rejected: 'rejected because',
    messages: 'Message hierarchy',
    mainPromise: 'Main promise',
    supporting: 'Supporting messages',
    order: 'Order of explanation',
    pillars: 'Content pillars',
    goal: 'goal',
    question: 'audience question',
    allowed: 'what we show',
    exclusions: 'what we do not',
    channel: 'Role of the channel',
    contact: 'contact path',
    limits: 'limits',
    measurement: 'Measurement hypothesis',
    signals: 'signals',
    baseline: 'baseline',
    unknownBaseline: 'none — without internal data we set no numeric target',
    causality: 'limit of inference',
    boundaries: 'Creative boundaries',
    notPromoted: 'Not promoted',
    prohibited: 'Not promised',
    creativity: 'Permitted creativity',
    rights: 'Rights to materials',
    assumptions: 'Open assumptions',
    proofArchitecture: 'Proof architecture (internal)',
    issues: 'Gaps and limitations',
    support: { declared_method: 'declared method', documented_capability: 'documented capability', demonstrated_result: 'demonstrated result' },
  },
} as const

function bullets(items: string[]): string {
  return items.length ? items.map((item) => `- ${item}`).join('\n') : '- —'
}

export function renderStrategiaClientView(args: { outputLanguage: 'pl' | 'en'; brand: string; data: StrategiaData }): ClientView {
  const { data } = args
  const t = T[args.outputLanguage]
  const supportOf = (claimIds: string[]): string => {
    const rows = data.proof_architecture.filter((row) => claimIds.includes(row.claim_id))
    if (!rows.length) return ''
    const strongest = rows.reduce((best, row) => (['declared_method', 'documented_capability', 'demonstrated_result'].indexOf(row.status) > ['declared_method', 'documented_capability', 'demonstrated_result'].indexOf(best.status) ? row : best))
    const limit = strongest.limitations[0]
    return ` _(${t.support[strongest.status]}${limit ? `; ${limit}` : ''})_`
  }
  const lines: string[] = [
    `# ${t.title} — ${args.brand}`,
    '',
    `## ${t.choice}`,
    `${data.strategic_choice.positioning} ${data.strategic_choice.rationale}`,
    `**${t.deprioritized}:** ${data.strategic_choice.deprioritized.join('; ') || '—'}`,
    '',
    `## ${t.tension}`,
    `**${t.wants}:** ${data.buyer_tension.desired_progress}`,
    `**${t.barrier}:** ${data.buyer_tension.barrier}`,
    `**${t.statusQuo}:** ${data.buyer_tension.status_quo_risk}`,
    `**${t.objection}** (${data.buyer_tension.objection_status === 'customer_voice' ? t.customerVoice : t.hypothesis}): ${data.buyer_tension.illustrative_objection}`,
    '',
    `## ${t.uvp}`,
    `**${data.uvp.working_sentence}**${supportOf([data.uvp.claim_id])}`,
    data.uvp.explanation.join(' '),
    `**${t.mechanism}:** ${data.uvp.mechanism}`,
    `**${t.alternative}:** ${data.uvp.alternative}`,
    `**${t.reasonToBelieve}:** ${data.uvp.reason_to_believe}`,
    `**${t.useConditions}:** ${data.uvp.use_conditions.join('; ') || '—'}`,
    '',
    ...(data.options_considered.length ? [`## ${t.options}`, ...data.options_considered.map((o) => `- **${o.direction}** — ${t.advantage}: ${o.advantage}; ${t.rejected}: ${o.rejection}`), ''] : []),
    `## ${t.messages}`,
    `**${t.mainPromise}:** ${data.message_hierarchy.main_promise.text}${supportOf(data.message_hierarchy.main_promise.claim_ids)}`,
    `**${t.supporting}:**`,
    ...data.message_hierarchy.supporting_messages.map((m) => `${m.order}. ${m.text}${supportOf(m.claim_ids)}`),
    `**${t.order}:** ${data.message_hierarchy.explanation_order.join(' → ')}`,
    '',
    `## ${t.pillars}`,
    ...data.pillars.map((p) => `- **${p.area}** — ${t.goal}: ${p.strategic_goal}; ${t.question}: ${p.audience_question}; ${t.allowed}: ${p.allowed_content.join(', ')}; ${t.exclusions}: ${p.exclusions.join(', ') || '—'}`),
    '',
    `## ${t.channel}`,
    `${data.channel_role.channel}: ${data.channel_role.role} ${data.channel_role.content_scope}`,
    `**${t.contact}:** ${data.channel_role.contact_path} · **${t.limits}:** ${data.channel_role.limits}`,
    '',
    `## ${t.measurement}`,
    data.measurement_hypothesis.hypothesis,
    `**${t.signals}:** ${data.measurement_hypothesis.observable_signals.join('; ')}`,
    `**${t.baseline}:** ${data.measurement_hypothesis.baseline ?? t.unknownBaseline}`,
    `**${t.causality}:** ${data.measurement_hypothesis.causality_limit}`,
    '',
    `## ${t.boundaries}`,
    `**${t.notPromoted}:** ${data.creative_boundaries.not_promoted.join('; ') || '—'}`,
    `**${t.prohibited}:** ${data.creative_boundaries.prohibited_promises.join('; ') || '—'}`,
    `**${t.creativity}:** ${data.creative_boundaries.permitted_creativity}`,
    `**${t.rights}:** ${data.creative_boundaries.rights}`,
    ...(data.creative_boundaries.open_assumptions.length ? [`**${t.assumptions}:** ${data.creative_boundaries.open_assumptions.join('; ')}`] : []),
    '',
  ]
  return checkClientView('WZR-STRATEGIA', lines.join('\n'))
}

/** Internal markdown: every field with its ids, support levels and the full proof architecture — for staff and QA. */
export function renderStrategia(args: { outputLanguage: 'pl' | 'en'; brand: string; data: StrategiaData; issues: DocumentIssue[] }): string {
  const { data } = args
  const t = T[args.outputLanguage]
  return [
    `# KLI-STRATEGIA — ${args.brand}`,
    '',
    `## ${t.choice} · ${data.strategic_choice.status}`,
    `${data.strategic_choice.positioning}`,
    `- audience: ${data.strategic_choice.audience} · situation: ${data.strategic_choice.situation} · category: ${data.strategic_choice.category}`,
    `- decision: ${data.strategic_choice.decision}`,
    `- ${t.deprioritized}: ${data.strategic_choice.deprioritized.join('; ') || '—'}`,
    `- rationale: ${data.strategic_choice.rationale}`,
    `- evidence: ${data.strategic_choice.evidence_ids.join(', ') || '—'}`,
    '',
    `## ${t.tension} · ${data.buyer_tension.objection_status}`,
    `- ${t.wants}: ${data.buyer_tension.desired_progress}`,
    `- ${t.barrier}: ${data.buyer_tension.barrier}`,
    `- ${t.objection}: ${data.buyer_tension.illustrative_objection}`,
    `- ${t.statusQuo}: ${data.buyer_tension.status_quo_risk}`,
    `- decision criterion: ${data.buyer_tension.decision_criterion.text ?? '—'} (${data.buyer_tension.decision_criterion.status}; ${data.buyer_tension.decision_criterion.origin})`,
    `- evidence: ${data.buyer_tension.evidence_ids.join(', ') || '—'} · ${data.buyer_tension.evidence_status}`,
    '',
    `## ${t.uvp} · ${data.uvp.claim_id} · ${data.uvp.support_level}`,
    `**${data.uvp.working_sentence}**`,
    ...data.uvp.explanation.map((line) => `- ${line}`),
    `- ${t.mechanism}: ${data.uvp.mechanism}`,
    `- ${t.alternative}: ${data.uvp.alternative} (${data.uvp.alternative_status})`,
    `- ${t.reasonToBelieve}: ${data.uvp.reason_to_believe}`,
    `- ${t.useConditions}: ${data.uvp.use_conditions.join('; ') || '—'}`,
    `- evidence: ${data.uvp.evidence_ids.join(', ') || '—'}`,
    '',
    `## ${t.options}`,
    bullets(data.options_considered.map((o) => `${o.direction} — ${o.advantage} / ${o.rejection}`)),
    '',
    `## ${t.proofArchitecture}`,
    ...data.proof_architecture.map((row) =>
      [
        `- **${row.claim_id}** [${row.status}] ${row.allowed_claim}`,
        `  - mechanism: ${row.mechanism}`,
        `  - proofs: ${row.proof_ids.join(', ') || '—'} · facts: ${row.fact_ids.join(', ') || '—'} · sources: ${row.source_ids.join(', ') || '—'}`,
        `  - limitations: ${row.limitations.join('; ') || '—'}`,
        `  - forbidden: ${row.forbidden_claim} · confirms: ${row.confirmation_owner}`,
      ].join('\n'),
    ),
    '',
    `## ${t.messages}`,
    `- ${t.mainPromise} [${data.message_hierarchy.main_promise.status}] ${data.message_hierarchy.main_promise.text} (${data.message_hierarchy.main_promise.claim_ids.join(', ') || '—'})`,
    ...data.message_hierarchy.supporting_messages.map((m) => `- ${m.order}. ${m.text} (${m.claim_ids.join(', ') || '—'}; ${m.fact_ids.join(', ') || '—'})`),
    `- ${t.order}: ${data.message_hierarchy.explanation_order.join(' → ')}`,
    '',
    `## ${t.pillars}`,
    ...data.pillars.map((p) => `- **${p.pillar_id} ${p.area}** — ${p.strategic_goal}; ${p.audience_question}; allowed: ${p.allowed_content.join(', ')}; excluded: ${p.exclusions.join(', ') || '—'}; claims: ${p.claim_ids.join(', ') || '—'}; seeds: ${p.seed_ids.join(', ') || '—'}`),
    '',
    `## ${t.channel}`,
    `- ${data.channel_role.channel}: ${data.channel_role.role}`,
    `- knowledge level: ${data.channel_role.knowledge_level} · scope: ${data.channel_role.content_scope}`,
    `- ${t.contact}: ${data.channel_role.contact_path} · owner: ${data.channel_role.contact_owner ?? '—'} · ${t.limits}: ${data.channel_role.limits}`,
    `- evidence: ${data.channel_role.evidence_ids.join(', ') || '—'}`,
    '',
    `## ${t.measurement}`,
    `- ${data.measurement_hypothesis.hypothesis}`,
    `- ${t.signals}: ${data.measurement_hypothesis.observable_signals.join('; ')}`,
    ...data.measurement_hypothesis.measures.map((m) => `- ${m.name}: ${m.definition}`),
    `- ${t.baseline}: ${data.measurement_hypothesis.baseline ?? '—'} · target: ${data.measurement_hypothesis.numerical_target ?? '—'}`,
    `- future test: ${data.measurement_hypothesis.future_test} · ${t.causality}: ${data.measurement_hypothesis.causality_limit}`,
    '',
    `## ${t.boundaries}`,
    `- ${t.notPromoted}: ${data.creative_boundaries.not_promoted.join('; ') || '—'}`,
    `- ${t.prohibited}: ${data.creative_boundaries.prohibited_promises.join('; ') || '—'}`,
    `- ${t.creativity}: ${data.creative_boundaries.permitted_creativity}`,
    `- ${t.rights}: ${data.creative_boundaries.rights}`,
    `- ${t.assumptions}: ${data.creative_boundaries.open_assumptions.join('; ') || '—'}`,
    `- plan effect: ${data.creative_boundaries.plan_effect} · research return required: ${data.creative_boundaries.research_return_required}`,
    '',
    `## ${t.issues} (${args.issues.length})`,
    bullets(args.issues.map((i) => `**${i.code}** (${i.severity}) ${i.detail}`)),
    '',
  ].join('\n')
}
